# Generated by Django 4.2.3 on 2023-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=60)),
                ('correo_electronico', models.CharField(max_length=70)),
                ('tipo_servicio', models.CharField(max_length=12)),
                ('celular', models.CharField(verbose_name=15)),
                ('act_usua', models.CharField(verbose_name=15)),
            ],
        ),
    ]
