# Generated by Django 4.2.3 on 2023-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_puro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='act_esta',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='clientes',
            name='act_hora',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_instalacion',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_plan',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='act_usua',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=15),
        ),
    ]
