# Generated by Django 4.2.3 on 2023-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_puro', '0002_alter_clientes_options_clientes_act_esta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='MacAdress',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
